before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: l0PhEgGqaHzuM7fq5+nbInZIOxtW8aq+9AfU7zxM2boykWoTq6A/vwFO7eyz/H+0TxBT5NbjY5gdt2yqNqZmiyGR1Q1v+G5iIbb4a7kuDHUWYuJnsyjdprMpEHSpGPZWwAjk2Vuod4rlrrporjjamGX0B7axpgHQvjgXTsFbb/4GocxYGGoaCVt7XnJO3aTRLnWVZ4BCxDKS4HeG9BaCHPSB91lMs0ITXu/InJ2QJfDWjhlkY9aBj8gN5Tf+NjkMhojL5vX6fhP0ZQUQXFSm09rfaDBG+2DZwu3/1VI+oUN191jcD4gqsv0Oba2eaQIJV1ul5M37/PjxRCy40xFCHVMBLZkkofAHKypgjuc7Esq+fPCNaEsJqndRyEjt+ucEDXr8MMkx2+wxxbz2QIsZvQ7Um7MJeTrIB9D9wj2xuiZzzaQU+1V+dKc8tkguXSo4Mj7epZLUs3pkQTGnemTOLjP/yL/fs2N+t9uiHioHFnX7KsCeRCk4QEkbRR1jN7ayYuX9k8q/eUmFIr12Wl7ISbYMNppgrkpmXiZF2VSr4sgG6bQtdSRiy2KvYyYLTVS8yHg6OsuKQFCiCrOaz/lpM1APwtOGJwmq4AW4F1jnGQ8PiNQDR2KWA3J6CZYZTgz8BgSLMKQHlDGPOUs0+nnFpMqcfdvNYsYbxFIaE9Eqc6Y= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
